// gal-ppt/src/components/Editor/Canvas.tsx
import { useEditorStore } from '@/store/editorStore';
import type { ComponentType, AnimationConfig } from '@/types';
import { useState, useRef, useEffect, useCallback } from 'react';
import { Lock, Unlock, Eye, EyeOff, Trash2, Move } from 'lucide-react';
import { clamp } from '@/utils';

export const Canvas = () => {
  const { 
    currentProject, 
    currentPageId, 
    selectedComponentId,
    selectComponent,
    addComponent,
    removeComponent,
    updateComponentPosition,
    updateComponentSize,
    toggleComponentLock,
    toggleComponentVisibility,
    zoom 
  } = useEditorStore();

  const canvasRef = useRef<HTMLDivElement>(null);
  const [isDragging, setIsDragging] = useState(false);
  const [isResizing, setIsResizing] = useState(false);
  const [dragStart, setDragStart] = useState({ x: 0, y: 0, componentX: 0, componentY: 0 });
  const [resizeStart, setResizeStart] = useState({ x: 0, y: 0, width: 0, height: 0 });
  const [resizeHandle, setResizeHandle] = useState<'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw' | null>(null);

  const currentPage = currentProject?.pages.find(p => p.id === currentPageId);
  const selectedComponent = currentPage?.components.find(c => c.id === selectedComponentId);

  const handleDragOver = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    e.dataTransfer.dropEffect = 'copy';
  }, []);

  const handleDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    const componentType = e.dataTransfer.getData('componentType') as ComponentType;
    const defaultProps = JSON.parse(e.dataTransfer.getData('defaultProps') || '{}');
    
    if (!componentType || !canvasRef.current) return;

    const rect = canvasRef.current.getBoundingClientRect();
    const x = (e.clientX - rect.left) / (zoom / 100);
    const y = (e.clientY - rect.top) / (zoom / 100);

    const defaultAnimation: AnimationConfig = {
      type: 'fade',
      duration: 500,
      delay: 0,
      easing: 'ease-out'
    };

    let width = 300;
    let height = 200;

    switch (componentType) {
      case 'background':
        width = 1920;
        height = 1080;
        break;
      case 'dialogue':
        width = 800;
        height = 150;
        break;
      case 'text':
        width = 400;
        height = 80;
        break;
      case 'choice':
        width = 300;
        height = 200;
        break;
      case 'button':
        width = 150;
        height = 50;
        break;
      case 'character':
        width = 400;
        height = 600;
        break;
      case 'audio':
        width = 200;
        height = 80;
        break;
      case 'transition':
        width = 100;
        height = 50;
        break;
    }

    addComponent({
      type: componentType,
      x: clamp(x - width / 2, 0, 1920 - width),
      y: clamp(y - height / 2, 0, 1080 - height),
      width,
      height,
      visible: true,
      locked: false,
      props: defaultProps,
      animation: defaultAnimation
    });
  }, [addComponent, zoom]);

  const handleCanvasClick = useCallback((e: React.MouseEvent) => {
    if (e.target === canvasRef.current) {
      selectComponent(null);
    }
  }, [selectComponent]);

  const handleComponentMouseDown = useCallback((e: React.MouseEvent, componentId: string) => {
    e.stopPropagation();
    const component = currentPage?.components.find(c => c.id === componentId);
    if (!component || component.locked) return;

    selectComponent(componentId);
    
    const rect = canvasRef.current?.getBoundingClientRect();
    if (!rect) return;

    setIsDragging(true);
    setDragStart({
      x: e.clientX,
      y: e.clientY,
      componentX: component.x,
      componentY: component.y
    });
  }, [selectComponent, currentPage]);

  const handleMouseMove = useCallback((e: React.MouseEvent) => {
    if (!canvasRef.current) return;
    
    if (isDragging && selectedComponentId) {
      const rect = canvasRef.current.getBoundingClientRect();
      const deltaX = (e.clientX - dragStart.x) / (zoom / 100);
      const deltaY = (e.clientY - dragStart.y) / (zoom / 100);
      
      const newX = clamp(dragStart.componentX + deltaX, 0, 1920 - (selectedComponent?.width || 0));
      const newY = clamp(dragStart.componentY + deltaY, 0, 1080 - (selectedComponent?.height || 0));
      
      updateComponentPosition(selectedComponentId, newX, newY);
    }
    
    if (isResizing && selectedComponentId) {
      const rect = canvasRef.current.getBoundingClientRect();
      const deltaX = (e.clientX - resizeStart.x) / (zoom / 100);
      const deltaY = (e.clientY - resizeStart.y) / (zoom / 100);
      
      let newWidth = resizeStart.width;
      let newHeight = resizeStart.height;
      let newX = selectedComponent?.x || 0;
      let newY = selectedComponent?.y || 0;

      if (resizeHandle?.includes('e')) {
        newWidth = clamp(resizeStart.width + deltaX, 50, 1920);
      }
      if (resizeHandle?.includes('w')) {
        newWidth = clamp(resizeStart.width - deltaX, 50, 1920);
        newX = clamp(resizeStart.width - newWidth + (selectedComponent?.x || 0), 0, 1920);
      }
      if (resizeHandle?.includes('s')) {
        newHeight = clamp(resizeStart.height + deltaY, 50, 1080);
      }
      if (resizeHandle?.includes('n')) {
        newHeight = clamp(resizeStart.height - deltaY, 50, 1080);
        newY = clamp(resizeStart.height - newHeight + (selectedComponent?.y || 0), 0, 1080);
      }
      
      updateComponentSize(selectedComponentId, newWidth, newHeight);
      if (resizeHandle?.includes('w')) {
        updateComponentPosition(selectedComponentId, newX, selectedComponent?.y || 0);
      }
      if (resizeHandle?.includes('n')) {
        updateComponentPosition(selectedComponentId, selectedComponent?.x || 0, newY);
      }
    }
  }, [isDragging, isResizing, selectedComponentId, dragStart, resizeStart, resizeHandle, zoom, selectedComponent, updateComponentPosition, updateComponentSize]);

  const handleMouseUp = useCallback((_e?: React.MouseEvent) => {
    setIsDragging(false);
    setIsResizing(false);
    setResizeHandle(null);
  }, []);

  const handleResizeMouseDown = useCallback((e: React.MouseEvent, handle: 'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw') => {
    e.stopPropagation();
    const component = currentPage?.components.find(c => c.id === selectedComponentId);
    if (!component || component.locked) return;

    setIsResizing(true);
    setResizeHandle(handle);
    setResizeStart({
      x: e.clientX,
      y: e.clientY,
      width: component.width,
      height: component.height
    });
  }, [selectedComponentId, currentPage]);

  useEffect(() => {
    const handleMouseMoveNative = (e: MouseEvent) => handleMouseMove({ clientX: e.clientX, clientY: e.clientY } as React.MouseEvent);
    const handleMouseUpNative = (e: MouseEvent) => handleMouseUp({ clientX: e.clientX, clientY: e.clientY } as React.MouseEvent);
    document.addEventListener('mousemove', handleMouseMoveNative);
    document.addEventListener('mouseup', handleMouseUpNative);
    return () => {
      document.removeEventListener('mousemove', handleMouseMoveNative);
      document.removeEventListener('mouseup', handleMouseUpNative);
    };
  }, [handleMouseMove, handleMouseUp]);

  if (!currentProject || !currentPage) return null;

  return (
    <div className="h-full flex items-center justify-center bg-gray-900/50 p-4">
      <div 
        ref={canvasRef}
        className="relative bg-black overflow-hidden rounded-lg shadow-2xl"
        style={{
          width: `${1920 * zoom / 100}px`,
          height: `${1080 * zoom / 100}px`,
          backgroundImage: 'linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px)',
          backgroundSize: `${40 * zoom / 100}px ${40 * zoom / 100}px`
        }}
        onDragOver={handleDragOver}
        onDrop={handleDrop}
        onClick={handleCanvasClick}
      >
        {currentPage.components
          .filter(c => c.visible)
          .sort((a, b) => a.zIndex - b.zIndex)
          .map((component) => {
            const isSelected = component.id === selectedComponentId;
            
            return (
              <div
                key={component.id}
                className={`
                  absolute cursor-move select-none transition-shadow
                  ${isSelected ? 'ring-2 ring-purple-500 ring-offset-2 ring-offset-black' : ''}
                  ${component.locked ? 'opacity-70' : ''}
                `}
                style={{
                  left: `${component.x * zoom / 100}px`,
                  top: `${component.y * zoom / 100}px`,
                  width: `${component.width * zoom / 100}px`,
                  height: `${component.height * zoom / 100}px`,
                  zIndex: component.zIndex,
                  opacity: component.visible ? 1 : 0,
                  transform: `scale(${zoom / 100})`,
                  transformOrigin: 'top left'
                }}
                onMouseDown={(e) => handleComponentMouseDown(e, component.id)}
              >
                {component.type === 'background' && (
                  <div 
                    className="absolute inset-0 bg-gradient-to-br from-gray-700 to-gray-900"
                    style={{
                      backgroundImage: component.props.imageUrl 
                        ? `url(${component.props.imageUrl})` 
                        : undefined,
                      backgroundSize: component.props.fit || 'cover',
                      backgroundPosition: 'center'
                    }}
                  />
                )}
                
                {component.type === 'character' && (
                  <div 
                    className="w-full h-full flex items-center justify-center bg-gray-700/50 border border-gray-600 rounded"
                    style={{
                      backgroundImage: component.props.imageUrl 
                        ? `url(${component.props.imageUrl})` 
                        : undefined,
                      backgroundSize: 'contain',
                      backgroundRepeat: 'no-repeat',
                      backgroundPosition: 'center bottom'
                    }}
                  >
                    {!component.props.imageUrl && (
                      <span className="text-gray-500 text-sm">角色立绘</span>
                    )}
                  </div>
                )}
                
                {component.type === 'dialogue' && (
                  <div className="w-full h-full bg-black/70 rounded-lg border border-gray-600 p-4 flex flex-col">
                    {component.props.characterName && (
                      <span className="text-purple-400 font-semibold mb-2">{component.props.characterName}</span>
                    )}
                    <span 
                      className="text-white flex-1"
                      style={{ fontSize: `${component.props.fontSize || 24}px`, color: component.props.textColor || '#ffffff' }}
                    >
                      {component.props.text || '对话文本'}
                    </span>
                  </div>
                )}
                
                {component.type === 'text' && (
                  <div className="w-full h-full flex items-center justify-center bg-gray-800/50 border border-gray-600 rounded">
                    <span 
                      className="text-white"
                      style={{ fontSize: `${component.props.fontSize || 32}px`, color: component.props.textColor || '#ffffff' }}
                    >
                      {component.props.text || '文本内容'}
                    </span>
                  </div>
                )}
                
                {component.type === 'choice' && (
                  <div className="w-full h-full bg-gray-800/70 rounded-lg border border-gray-600 p-4 flex flex-col gap-2">
                    {(component.props.options || []).map((option, index) => (
                      <button 
                        key={index}
                        className="px-4 py-2 bg-gray-700 hover:bg-purple-600 rounded-lg text-white transition-colors"
                      >
                        {option.text || `选项${index + 1}`}
                      </button>
                    ))}
                  </div>
                )}
                
                {component.type === 'button' && (
                  <button className="w-full h-full bg-gradient-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 rounded-lg text-white font-medium transition-all">
                    {component.props.text || '按钮'}
                  </button>
                )}
                
                {component.type === 'audio' && (
                  <div className="w-full h-full bg-gray-800/70 rounded-lg border border-gray-600 p-3 flex items-center gap-3">
                    <div className="w-8 h-8 bg-purple-600 rounded-full flex items-center justify-center">
                      <span className="text-white">🎵</span>
                    </div>
                    <span className="text-white text-sm flex-1 truncate">
                      {component.props.audioUrl ? '已添加音效' : '音效组件'}
                    </span>
                  </div>
                )}
                
                {component.type === 'transition' && (
                  <div className="w-full h-full bg-blue-900/50 rounded-lg border border-blue-500 p-2 flex items-center justify-center">
                    <span className="text-blue-400 text-sm">→ {component.props.targetPageId ? '跳转' : '转场'}</span>
                  </div>
                )}

                {isSelected && !component.locked && (
                  <>
                    <div className="absolute -top-8 left-0 right-0 flex gap-1">
                      <button
                        onClick={(e) => { e.stopPropagation(); toggleComponentVisibility(component.id); }}
                        className="p-1 bg-gray-800 hover:bg-gray-700 rounded"
                      >
                        <Eye size={14} className="text-white" />
                      </button>
                      <button
                        onClick={(e) => { e.stopPropagation(); toggleComponentLock(component.id); }}
                        className="p-1 bg-gray-800 hover:bg-gray-700 rounded"
                      >
                        {component.locked ? <Lock size={14} className="text-yellow-400" /> : <Unlock size={14} className="text-white" />}
                      </button>
                      <button
                        onClick={(e) => { e.stopPropagation(); removeComponent(component.id); }}
                        className="p-1 bg-gray-800 hover:bg-red-600 rounded"
                      >
                        <Trash2 size={14} className="text-red-400" />
                      </button>
                    </div>
                    
                    <div 
                      className="absolute -left-2 -top-2 w-3 h-3 bg-purple-500 rounded-full cursor-nw-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'nw')}
                    />
                    <div 
                      className="absolute -right-2 -top-2 w-3 h-3 bg-purple-500 rounded-full cursor-ne-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'ne')}
                    />
                    <div 
                      className="absolute -left-2 -bottom-2 w-3 h-3 bg-purple-500 rounded-full cursor-sw-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'sw')}
                    />
                    <div 
                      className="absolute -right-2 -bottom-2 w-3 h-3 bg-purple-500 rounded-full cursor-se-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'se')}
                    />
                    <div 
                      className="absolute -left-2 top-1/2 -translate-y-1/2 w-3 h-3 bg-purple-500 rounded-full cursor-w-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'w')}
                    />
                    <div 
                      className="absolute -right-2 top-1/2 -translate-y-1/2 w-3 h-3 bg-purple-500 rounded-full cursor-e-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'e')}
                    />
                    <div 
                      className="absolute left-1/2 -translate-x-1/2 -top-2 w-3 h-3 bg-purple-500 rounded-full cursor-n-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 'n')}
                    />
                    <div 
                      className="absolute left-1/2 -translate-x-1/2 -bottom-2 w-3 h-3 bg-purple-500 rounded-full cursor-s-resize"
                      onMouseDown={(e) => handleResizeMouseDown(e, 's')}
                    />
                  </>
                )}
              </div>
            );
          })}

        {currentPage.components.length === 0 && (
          <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-500">
            <Move size={48} className="mb-4 opacity-50" />
            <p className="text-lg">拖拽组件到此处</p>
            <p className="text-sm mt-2">从左侧组件库选择组件</p>
          </div>
        )}
      </div>
    </div>
  );
};

// src/components/Editor/Canvas.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useEditorStore } from '@/stores/editorStore'
import type { ComponentType, AnimationConfig } from '@/types'
import { clamp } from '@/utils'

const store = useEditorStore()
const canvasRef = ref<HTMLDivElement | null>(null)

const isDragging = ref(false)
const isResizing = ref(false)
const dragStart = ref({ x: 0, y: 0, componentX: 0, componentY: 0 })
const resizeStart = ref({ x: 0, y: 0, width: 0, height: 0 })
const resizeHandle = ref<'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw' | null>(null)

const currentPage = computed(() => {
  return store.currentProject?.pages.find(p => p.id === store.currentPageId)
})

const selectedComponent = computed(() => {
  return currentPage.value?.components.find(c => c.id === store.selectedComponentId)
})

function handleDragOver(e: DragEvent) {
  e.preventDefault()
  if (e.dataTransfer) e.dataTransfer.dropEffect = 'copy'
}

function handleDrop(e: DragEvent) {
  e.preventDefault()
  if (!canvasRef.value) return
  const componentType = e.dataTransfer?.getData('componentType') as ComponentType
  const defaultPropsStr = e.dataTransfer?.getData('defaultProps') || '{}'
  if (!componentType) return
  const defaultProps = JSON.parse(defaultPropsStr)

  const rect = canvasRef.value.getBoundingClientRect()
  const x = (e.clientX - rect.left) / (store.zoom / 100)
  const y = (e.clientY - rect.top) / (store.zoom / 100)

  const defaultAnimation: AnimationConfig = {
    type: 'fade',
    duration: 500,
    delay: 0,
    easing: 'ease-out'
  }

  let width = 300
  let height = 200

  switch (componentType) {
    case 'background': width = 1920; height = 1080; break
    case 'dialogue': width = 800; height = 150; break
    case 'text': width = 400; height = 80; break
    case 'choice': width = 300; height = 200; break
    case 'button': width = 150; height = 50; break
    case 'character': width = 400; height = 600; break
    case 'audio': width = 200; height = 80; break
    case 'transition': width = 100; height = 50; break
  }

  store.addComponent({
    type: componentType,
    x: clamp(x - width / 2, 0, 1920 - width),
    y: clamp(y - height / 2, 0, 1080 - height),
    width,
    height,
    visible: true,
    locked: false,
    props: defaultProps,
    animation: defaultAnimation
  })
}

function handleCanvasClick(e: MouseEvent) {
  if (e.target === canvasRef.value) {
    store.selectComponent(null)
  }
}

function handleComponentMouseDown(e: MouseEvent, componentId: string) {
  e.stopPropagation()
  const component = currentPage.value?.components.find(c => c.id === componentId)
  if (!component || component.locked) return

  store.selectComponent(componentId)
  isDragging.value = true
  dragStart.value = {
    x: e.clientX,
    y: e.clientY,
    componentX: component.x,
    componentY: component.y
  }
}

function handleResizeMouseDown(e: MouseEvent, handle: 'n' | 's' | 'e' | 'w' | 'ne' | 'nw' | 'se' | 'sw') {
  e.stopPropagation()
  if (!selectedComponent.value || selectedComponent.value.locked) return
  isResizing.value = true
  resizeHandle.value = handle
  resizeStart.value = {
    x: e.clientX,
    y: e.clientY,
    width: selectedComponent.value.width,
    height: selectedComponent.value.height
  }
}

function handleMouseMove(e: MouseEvent) {
  if (!canvasRef.value) return

  if (isDragging.value && store.selectedComponentId) {
    const deltaX = (e.clientX - dragStart.value.x) / (store.zoom / 100)
    const deltaY = (e.clientY - dragStart.value.y) / (store.zoom / 100)
    const newX = clamp(dragStart.value.componentX + deltaX, 0, 1920 - (selectedComponent.value?.width || 0))
    const newY = clamp(dragStart.value.componentY + deltaY, 0, 1080 - (selectedComponent.value?.height || 0))
    store.updateComponentPosition(store.selectedComponentId, newX, newY)
  }

  if (isResizing.value && store.selectedComponentId) {
    const deltaX = (e.clientX - resizeStart.value.x) / (store.zoom / 100)
    const deltaY = (e.clientY - resizeStart.value.y) / (store.zoom / 100)

    let newWidth = resizeStart.value.width
    let newHeight = resizeStart.value.height
    let newX = selectedComponent.value?.x || 0
    let newY = selectedComponent.value?.y || 0

    if (resizeHandle.value?.includes('e')) {
      newWidth = clamp(resizeStart.value.width + deltaX, 50, 1920)
    }
    if (resizeHandle.value?.includes('w')) {
      newWidth = clamp(resizeStart.value.width - deltaX, 50, 1920)
      newX = clamp(resizeStart.value.width - newWidth + (selectedComponent.value?.x || 0), 0, 1920)
    }
    if (resizeHandle.value?.includes('s')) {
      newHeight = clamp(resizeStart.value.height + deltaY, 50, 1080)
    }
    if (resizeHandle.value?.includes('n')) {
      newHeight = clamp(resizeStart.value.height - deltaY, 50, 1080)
      newY = clamp(resizeStart.value.height - newHeight + (selectedComponent.value?.y || 0), 0, 1080)
    }

    store.updateComponentSize(store.selectedComponentId, newWidth, newHeight)
    if (resizeHandle.value?.includes('w')) {
      store.updateComponentPosition(store.selectedComponentId, newX, selectedComponent.value?.y || 0)
    }
    if (resizeHandle.value?.includes('n')) {
      store.updateComponentPosition(store.selectedComponentId, selectedComponent.value?.x || 0, newY)
    }
  }
}

function handleMouseUp() {
  isDragging.value = false
  isResizing.value = false
  resizeHandle.value = null
}

onMounted(() => {
  document.addEventListener('mousemove', handleMouseMove)
  document.addEventListener('mouseup', handleMouseUp)
})

onUnmounted(() => {
  document.removeEventListener('mousemove', handleMouseMove)
  document.removeEventListener('mouseup', handleMouseUp)
})
</script>

<template>
  <div v-if="store.currentProject && currentPage" class="canvas-wrapper">
    <div
      ref="canvasRef"
      class="canvas-area"
      :style="{
        width: `${1920 * store.zoom / 100}px`,
        height: `${1080 * store.zoom / 100}px`
      }"
      @dragover="handleDragOver"
      @drop="handleDrop"
      @click="handleCanvasClick"
    >
      <div
        v-for="component in [...currentPage.components].filter(c => c.visible).sort((a, b) => a.zIndex - b.zIndex)"
        :key="component.id"
        :class="['canvas-component', { selected: component.id === store.selectedComponentId, locked: component.locked }]"
        :style="{
          left: `${component.x * store.zoom / 100}px`,
          top: `${component.y * store.zoom / 100}px`,
          width: `${component.width * store.zoom / 100}px`,
          height: `${component.height * store.zoom / 100}px`,
          zIndex: component.zIndex
        }"
        @mousedown="handleComponentMouseDown($event, component.id)"
      >
        <!-- Background -->
        <div
          v-if="component.type === 'background'"
          class="comp-background"
          :style="{
            backgroundImage: component.props.imageUrl ? `url(${component.props.imageUrl})` : undefined,
            backgroundSize: component.props.fit || 'cover',
            backgroundPosition: 'center'
          }"
        />

        <!-- Character -->
        <div
          v-if="component.type === 'character'"
          class="comp-character"
          :style="{
            backgroundImage: component.props.imageUrl ? `url(${component.props.imageUrl})` : undefined,
            backgroundSize: 'contain',
            backgroundRepeat: 'no-repeat',
            backgroundPosition: 'center bottom'
          }"
        >
          <span v-if="!component.props.imageUrl" class="comp-placeholder">角色立绘</span>
        </div>

        <!-- Dialogue -->
        <div v-if="component.type === 'dialogue'" class="comp-dialogue">
          <span v-if="component.props.characterName" class="dialogue-name">{{ component.props.characterName }}</span>
          <span :style="{ fontSize: `${component.props.fontSize || 24}px`, color: component.props.textColor || '#ffffff' }">
            {{ component.props.text || '对话文本' }}
          </span>
        </div>

        <!-- Text -->
        <div v-if="component.type === 'text'" class="comp-text">
          <span :style="{ fontSize: `${component.props.fontSize || 32}px`, color: component.props.textColor || '#ffffff' }">
            {{ component.props.text || '文本内容' }}
          </span>
        </div>

        <!-- Choice -->
        <div v-if="component.type === 'choice'" class="comp-choice">
          <button v-for="(option, idx) in (component.props.options || [])" :key="idx" class="choice-option">
            {{ option.text || `选项${idx + 1}` }}
          </button>
        </div>

        <!-- Button -->
        <button v-if="component.type === 'button'" class="comp-button">
          {{ component.props.text || '按钮' }}
        </button>

        <!-- Audio -->
        <div v-if="component.type === 'audio'" class="comp-audio">
          <span class="audio-icon">🎵</span>
          <span class="audio-label">{{ component.props.audioUrl ? '已添加音效' : '音效组件' }}</span>
        </div>

        <!-- Transition -->
        <div v-if="component.type === 'transition'" class="comp-transition">
          → {{ component.props.targetPageId ? '跳转' : '转场' }}
        </div>

        <!-- Selection handles -->
        <template v-if="component.id === store.selectedComponentId && !component.locked">
          <div class="handle-toolbar">
            <button class="handle-btn" @click.stop="store.toggleComponentVisibility(component.id)">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
            </button>
            <button class="handle-btn" @click.stop="store.toggleComponentLock(component.id)">
              <svg v-if="component.locked" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="#facc15" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="0"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
              <svg v-else width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="0"/><path d="M7 11V7a5 5 0 0 1 9.9-1"/></svg>
            </button>
            <button class="handle-btn delete" @click.stop="store.removeComponent(component.id)">
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><polyline points="3 6 5 6 21 6"/><path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2"/></svg>
            </button>
          </div>

          <div class="resize-handle nw" @mousedown.stop="handleResizeMouseDown($event, 'nw')"></div>
          <div class="resize-handle ne" @mousedown.stop="handleResizeMouseDown($event, 'ne')"></div>
          <div class="resize-handle sw" @mousedown.stop="handleResizeMouseDown($event, 'sw')"></div>
          <div class="resize-handle se" @mousedown.stop="handleResizeMouseDown($event, 'se')"></div>
          <div class="resize-handle w" @mousedown.stop="handleResizeMouseDown($event, 'w')"></div>
          <div class="resize-handle e" @mousedown.stop="handleResizeMouseDown($event, 'e')"></div>
          <div class="resize-handle n" @mousedown.stop="handleResizeMouseDown($event, 'n')"></div>
          <div class="resize-handle s" @mousedown.stop="handleResizeMouseDown($event, 's')"></div>
        </template>
      </div>

      <div v-if="currentPage.components.length === 0" class="canvas-empty">
        <svg width="48" height="48" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" style="opacity:0.3;margin-bottom:16px;"><polyline points="5 9 2 12 5 15"/><polyline points="9 5 12 2 15 5"/><polyline points="15 19 12 22 9 19"/><polyline points="19 9 22 12 19 15"/><line x1="2" y1="12" x2="22" y2="12"/><line x1="12" y1="2" x2="12" y2="22"/></svg>
        <p style="font-size: 16px; font-weight: 700; font-style: italic;">拖拽组件到此处</p>
        <p class="p5r-subtitle" style="margin-top: 8px;">从左侧组件库选择组件</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.canvas-wrapper {
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: var(--p5r-black);
  padding: 16px;
  overflow: auto;
}

.canvas-area {
  position: relative;
  background: #050505;
  overflow: hidden;
  box-shadow: 0 0 40px rgba(216, 25, 33, 0.08);
  border: 1px solid var(--p5r-border);
  background-image:
    linear-gradient(rgba(255,255,255,0.02) 1px, transparent 1px),
    linear-gradient(90deg, rgba(255,255,255,0.02) 1px, transparent 1px);
}

.canvas-component {
  position: absolute;
  cursor: move;
  user-select: none;
  transition: box-shadow 0.15s;
}

.canvas-component.selected {
  outline: 2px solid var(--p5r-red);
  outline-offset: 2px;
}

.canvas-component.locked {
  opacity: 0.7;
}

/* Component types */
.comp-background {
  position: absolute;
  inset: 0;
  background: linear-gradient(135deg, #1a1a1a, #0a0a0a);
}

.comp-character {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(20, 20, 20, 0.5);
  border: 1px solid var(--p5r-border);
}

.comp-placeholder {
  color: var(--p5r-text-muted);
  font-size: 13px;
}

.comp-dialogue {
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.75);
  border: 1px solid var(--p5r-red);
  padding: 16px;
  display: flex;
  flex-direction: column;
}

.dialogue-name {
  color: var(--p5r-red);
  font-weight: 700;
  font-style: italic;
  margin-bottom: 8px;
}

.comp-text {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
  background: rgba(20, 20, 20, 0.5);
  border: 1px solid var(--p5r-border);
}

.comp-choice {
  width: 100%;
  height: 100%;
  background: rgba(20, 20, 20, 0.7);
  border: 1px solid var(--p5r-border);
  padding: 16px;
  display: flex;
  flex-direction: column;
  gap: 8px;
}

.choice-option {
  padding: 8px 16px;
  background: var(--p5r-dark);
  border: 1px solid var(--p5r-border);
  color: var(--p5r-cream);
  cursor: pointer;
  font-size: 13px;
}

.choice-option:hover {
  border-color: var(--p5r-red);
  background: rgba(216, 25, 33, 0.15);
}

.comp-button {
  width: 100%;
  height: 100%;
  background: var(--p5r-red);
  color: var(--p5r-white);
  border: none;
  cursor: pointer;
  font-weight: 700;
  font-style: italic;
  font-size: 14px;
}

.comp-audio {
  width: 100%;
  height: 100%;
  background: rgba(20, 20, 20, 0.7);
  border: 1px solid var(--p5r-border);
  padding: 12px;
  display: flex;
  align-items: center;
  gap: 12px;
}

.audio-icon {
  width: 32px;
  height: 32px;
  background: var(--p5r-red);
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 14px;
}

.audio-label {
  color: var(--p5r-cream);
  font-size: 13px;
  flex: 1;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.comp-transition {
  width: 100%;
  height: 100%;
  background: rgba(30, 10, 20, 0.5);
  border: 1px solid var(--p5r-red);
  display: flex;
  align-items: center;
  justify-content: center;
  color: var(--p5r-red);
  font-size: 13px;
  font-weight: 700;
  font-style: italic;
}

/* Handles */
.handle-toolbar {
  position: absolute;
  top: -32px;
  left: 0;
  right: 0;
  display: flex;
  gap: 4px;
}

.handle-btn {
  padding: 4px;
  background: var(--p5r-dark);
  border: 1px solid var(--p5r-border);
  color: var(--p5r-cream);
  cursor: pointer;
}

.handle-btn:hover {
  border-color: var(--p5r-red);
}

.handle-btn.delete {
  color: var(--p5r-red);
}

.resize-handle {
  position: absolute;
  width: 8px;
  height: 8px;
  background: var(--p5r-red);
}

.resize-handle.nw { top: -4px; left: -4px; cursor: nw-resize; }
.resize-handle.ne { top: -4px; right: -4px; cursor: ne-resize; }
.resize-handle.sw { bottom: -4px; left: -4px; cursor: sw-resize; }
.resize-handle.se { bottom: -4px; right: -4px; cursor: se-resize; }
.resize-handle.n { top: -4px; left: 50%; transform: translateX(-50%); cursor: n-resize; }
.resize-handle.s { bottom: -4px; left: 50%; transform: translateX(-50%); cursor: s-resize; }
.resize-handle.w { left: -4px; top: 50%; transform: translateY(-50%); cursor: w-resize; }
.resize-handle.e { right: -4px; top: 50%; transform: translateY(-50%); cursor: e-resize; }

.canvas-empty {
  position: absolute;
  inset: 0;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: var(--p5r-text-muted);
}
</style>
