// gal-ppt/src/pages/Preview.tsx
import { useEffect } from 'react';
import { useEditorStore } from '@/store/editorStore';
import { useGameStore } from '@/store/gameStore';
import { GameCanvas } from '@/components/Game/GameCanvas';
import { ControlBar } from '@/components/Game/ControlBar';

interface PreviewProps {
  onClose: () => void;
}

export const Preview = ({ onClose }: PreviewProps) => {
  const { currentProject } = useEditorStore();
  const { setProject, startGame } = useGameStore();

  useEffect(() => {
    if (currentProject) {
      setProject(currentProject);
      startGame();
    }
  }, [currentProject, setProject, startGame]);

  return (
    <div className="fixed inset-0 bg-black z-50">
      <GameCanvas />
      <ControlBar onClose={onClose} />
    </div>
  );
};

// src/pages/Preview.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useEditorStore } from '@/stores/editorStore'
import { useGameStore } from '@/stores/gameStore'
import GameCanvas from '@/components/Game/GameCanvas.vue'
import ControlBar from '@/components/Game/ControlBar.vue'

const props = defineProps<{
  onClose: () => void
}>()

const editorStore = useEditorStore()
const gameStore = useGameStore()

onMounted(() => {
  if (editorStore.currentProject) {
    gameStore.setProject(editorStore.currentProject)
    gameStore.startGame()
  }
})
</script>

<template>
  <div class="preview-page">
    <GameCanvas />
    <ControlBar :on-close="props.onClose" />
  </div>
</template>

<style scoped>
.preview-page {
  position: fixed;
  inset: 0;
  background: black;
  z-index: 50;
}
</style>
